### ISSUE TITLE
Compilation fails on clang++

### ISSUE THREAD

**Issue by mrzzzrm** [cginternals/glbinding#123]
Builds fine with gcc, yet clang 3.4 complains about:

```
.../glbinding/source/glbinding/source/Meta_BitfieldsByString.cpp:297:5: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    Meta_BitfieldsByString_0,
    ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [source/glbinding/CMakeFiles/glbinding.dir/source/Meta_BitfieldsByString.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
.../glbinding/source/glbinding/source/Meta_EnumsByString.cpp:4699:5: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    Meta_EnumsByString_0,
    ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

C++11's initializers are beyond my current understanding, are the map initializations in Meta_BitfieldsByString.cpp actually valid C++?

**Comment by scheibel** [comment]
We're working on it.

**Comment by mrzzzrm** [comment]
There are problems with the empty maps now:

```
.../glbinding/source/glbinding/source/Meta_BitfieldsByString.cpp:138:51: error: chosen constructor is explicit in copy-initialization
const std::unordered_map<std::string, GLbitfield> Meta_BitfieldsByString_J =
                                                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/unordered_map.h:138:7: note: constructor declared here
      unordered_map(size_type __n = 10,
      ^
.../glbinding/source/glbinding/source/Meta_BitfieldsByString.cpp:143:51: error: chosen constructor is explicit in copy-initialization
const std::unordered_map<std::string, GLbitfield> Meta_BitfieldsByString_K =
                                                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/unordered_map.h:138:7: note: constructor declared here
      unordered_map(size_type __n = 10,
      ^
.../glbinding/source/glbinding/source/Meta_BitfieldsByString.cpp:196:51: error: chosen constructor is explicit in copy-initialization
const std::unordered_map<std::string, GLbitfield> Meta_BitfieldsByString_O =
                                                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/unordered_map.h:138:7: note: constructor declared here
      unordered_map(size_type __n = 10,
      ^
.../glbinding/source/glbinding/source/Meta_BitfieldsByString.cpp:275:51: error: chosen constructor is explicit in copy-initialization
const std::unordered_map<std::string, GLbitfield> Meta_BitfieldsByString_W =
                                                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/unordered_map.h:138:7: note: constructor declared here
      unordered_map(size_type __n = 10,
      ^
.../glbinding/source/glbinding/source/Meta_BitfieldsByString.cpp:280:51: error: chosen constructor is explicit in copy-initialization
const std::unordered_map<std::string, GLbitfield> Meta_BitfieldsByString_X =
                                                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/unordered_map.h:138:7: note: constructor declared here
      unordered_map(size_type __n = 10,
      ^
.../glbinding/source/glbinding/source/Meta_BitfieldsByString.cpp:285:51: error: chosen constructor is explicit in copy-initialization
const std::unordered_map<std::string, GLbitfield> Meta_BitfieldsByString_Y =
                                                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/unordered_map.h:138:7: note: constructor declared here
      unordered_map(size_type __n = 10,
      ^
.../glbinding/source/glbinding/source/Meta_BitfieldsByString.cpp:290:51: error: chosen constructor is explicit in copy-initialization
const std::unordered_map<std::string, GLbitfield> Meta_BitfieldsByString_Z =
                                                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/unordered_map.h:138:7: note: constructor declared here
      unordered_map(size_type __n = 10,
      ^
7 errors generated.
```

**Comment by cgcostume** [comment]
jepp, we're already investigating this - which compiler version do you have (our jenkins uses 3.5, @scheibel tests on 3.6)

**Comment by cgcostume** [comment]
ok - all our build systems are warning free now - sorry for the small mess.

**Comment by mrzzzrm** [comment]
All green on clang 3.4!
