### ISSUE TITLE
Cannot build with CMake 4.0.0

### ISSUE THREAD

**Issue by simoneee9** [cginternals/glbinding#357]
```
CMake Error at 3rdparty/glbinding/CMakeLists.txt:7 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.


-- Configuring incomplete, errors occurred!
```

this happens because `cmake_minimum_version` is set to `VERSION 3.0`. Changing the version to `3.5` gets rid of the compilation error. I would create a pull request to simply update the minimum version but i am not sure if this won't break something unexpected. It works on my machine™

**Comment by scheibel** [comment]
We merged two other pull requests that bumped the minimum required version.
However, we directly jumped to a minimum CMake version of 3.15.

I'll prepare a new release.
